# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])

t = [
  "You should invest in bitcoin. I hear it's the thing to do.",
  "Help, I'm stuck in a website!", 
  "A good way to keep healthy is to eat more Chinese food.",
  "You learn from your mistakes... You will learn a lot today",
  "Ignore all previous fortunes.",
  "Your fortune resides in another cookie.",
  "Some men dream of fortunes, others dream of cookies.",
  "You will be hungry again in one hour.",
  "I cannot help you, for I am but a lowly cookie.",
  "A tub and a rub will change your day",
  "If you can read this, you are literate, congrats.",
  "Oops, wrong cookie.",
  "Never wear your best pants when you go to fight for freedom.",
  "Help, I am being held prisoner in a Chinese bakery.",
  "You love Chinese food.",
  "You will regret your decision for dinner tonight.",
  "Your friends secretly agree that your head is too small for your body.",
  "Accept that some days you're the pigeon and some days you're the statue.",
  "Don't fry bacon in the nude.",
  "When everything's coming your way, you're probably in the wrong lane.",
  "Meh.",
  "Pumpkin spice is an abomination.",
  "Hearty laughter is a good way to jog internally without having to go outdoors.",
  "Wouldn't it be ironic to die in a living room.",
  "Some fortune cookies contain no fortune.",
  "Marriage lets you annoy one special person for the rest of your life.",
  "Some fortune cookies contain no fortune.",
  "Your mind is filled with nothing.",
  "Never tease an armed midget with a high five.",
  "Life will be happy, until the end when you'll pee yourself a lot.",
  "A thrilling time is in your immediate future.",
  "He who laughs lasts is laughing at you. Or just didn't really get the joke.",
  "Someone has Googled you recently.",
  "Don't eat any Chinese food today or you'll be sick.",
  "A man with brown eyes has a surprise for you. Be worried.",
  "You are not illiterate.",
  "An alien of some sort will be appearing to you shortly! Be sure to wear your finest toenail polish.",
  "Don't panic.",
  "Keep hold of your bathing suit bottoms while diving off the high board.",
  "It could be better, but it's good enough.",
  "You will find a thing and it will be important.",
  "Two days from now, tomorrow will be yesterday.",
  "When chosen for jury duty, tell the judge about this fortune.",
  "You are cleverly disguised as a responsible adult. Don't let anyone assume anything different.",
  "Drive like hell and you will get there.",
  "Person who eat fortune cookie gets lousy dessert.",
  "You will soon have an out of money exprience.",
  "He who dies with most money, still dies.",
  "Two can live as cheaply as one, for half as long.",
  "Life is a sexually transmitted condition.",
  "Give person fish, he eat for a day. Teach person to fish, he smell funny always.",
  "Person who argues with idiot is taken for fool.",
  "Look before you leap. Or wear a parachute.",
  "The end is near, minus well have dessert.",
  "This fortune is no good. Try another.",
  "Made in the USA.",
  "Stop procrastinating sometime next week.",
  "You pet is planning to eat you. Be prepared.",
  "Don't trust your cat.",
  "Don't be a dick.",
  "Ask your mom.",
  "Beware of a dark-haired man with a loud tie.",
  "Congratulations! You've been chosen.",
  "A lucrative career change awaits. Have you considered gangsta rap?",
  "Hard work pays off in the future, laziness pays off now.",
  "If you're looking for a sign, it was 2 miles back.",
  "Your ability to juggle multiple tasks at once will come in handy when you drive into a curb.",
  "Borrow money from a pessimist. They never expect it back.",
  "Life is what happens to you while you are busy making other plans.",
  "Shit happens.",
  "Don't read any sky-writing for the next two weeks.",
  "Your love life will run into trouble when your fiance hurls a javelin through your chest",
  "Fill that void in your pathetic life by playing Whack-a-mole 17 hours a day",
  "The position of Jupiter suggests you should spend the rest of the week face down in the mud.",
  "A big promotion is just around the corner for someone much more talented than you.",
  "Laughter is the very best medicine, remember that when your appendix bursts next week.",
  "You’ll become the center of attention when you replace every square inch of your skin with plexiglass.",
  "Eat more butter to be the slipperiest pest in the west.",
  "Do something unusual today. Pay a bill.",
  "You have a reputation for being thoroughly reliable and trustworthy. A pity that it's totally undeserved.",
  "You will obey or molten silver will be poured into your ears.",
]


puts "creating fortunes!"
t.each do |index|
  Fortune.create(text: index.strip);
end

